name = "MoCreate"
author = "MoSadie"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a846925f81d2a764a7cb22887457bf506e6be27f390dc2f012d3aeaca48b5b10"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.128"
