name = "MoCreate"
author = "MoSadie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7805674e8acad8abf64ce0e035bac22c0862750d73a88125dc9cbf1613a605ba"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.128"
